# test out a tensorflow base image that works on Frink
FROM tensorflow/tensorflow:1.13.0rc1-py3-jupyter

# install some useful packages
# update and add packages for opencv
#RUN apt-get update
#RUN apt-get install -y libsm6 libxext6 libxrender-dev

# install python packages needed
#RUN pip install --upgrade pip && \
#	pip install opencv-python && \
#	pip install pillow tqdm scikit-learn
